version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: